name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Continuous Integration (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install packages
        run: pnpm install

      - name: Run tests
        run: pnpm run test

  cd:
    name: Continuous Deployment (CD)
    runs-on: ubuntu-latest
    needs: ci

    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: whoami
